version: "3"

services:
  im-printer:
    container_name: im-printer
    build:
      context: ./printer
      dockerfile: Dockerfile.dev
    volumes:
      - ./printer:/app
    ports:
      - 3002:3002
    networks:
      - main
  im-server:
    container_name: im-server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - storage:/storage
    ports:
      - 3000:3000
    networks:
      - main
  im-client:
    container_name: im-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
    ports:
      - 5173:5173
    networks:
      - main
  im-db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    networks:
      - main
  im-supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    depends_on:
      - im-db
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://myuser:mypassword@im-db:5432/mydb"
    networks:
      - main
    restart: unless-stopped
networks:
  main:
volumes:
  pgdata:
  storage:
