services:
  # PostgreSQL database
  - type: postgres
    name: my-postgres-db
    plan: starter

  # Express API Backend
  # - type: web
  #   name: my-express-api
  #   env: node
  #   buildCommand: cd server && npm install && npm run build
  #   startCommand: cd server && npm start
  #   envVars:
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: my-postgres-db
  #         property: connectionString

  # Vite React Frontend
  - type: static
    name: my-react-frontend
    buildCommand: cd client && npm install && npm run build
    publishDir: client/dist
    envVars:
      - key: REACT_APP_API_URL
        value: https://my-express-api.onrender.com

  # SuperTokens Core
  - type: web
    name: supertokens-core
    dockerfilePath: ./Dockerfile
    env: docker
    envVars:
      - key: SUPERTOKENS_CONFIG
        value: >
          connectionURI=postgresql://username:password@my-postgres-db:5432/supertokens;
          api_keys=your_api_key
      - key: SUPERTOKENS_API_KEY
        value: your_api_key

# Specify environment variables for database access in SuperTokens and the backend app
envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: my-postgres-db
      property: connectionString

# Define any required custom domains, replacing `example.com` with your actual domain
customDomains:
  - service: my-react-frontend
    domain: www.example.com
  - service: my-express-api
    domain: api.example.com
