services:
  - type: web
    name: income-mapper-server
    runtime: docker
    rootDir: server
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: income-mapper-db
          property: connectionString

  # Vite React Frontend
  - type: web
    runtime: static
    name: income-mapper-client
    env: node
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: REACT_APP_API_URL
        value: https://my-express-api.onrender.com
      - key: BACKEND_URL
        value: https://my-express-api.onrender.com/

  # SuperTokens Core
  - type: pserv
    runtime: docker
    name: supertokens-core
    rootDir: supertokens
    envVars:
      - key: SUPERTOKENS_API_KEY
        value: your_api_key

databases:
  - name: income-mapper-db
    databaseName: mydb
