services:
  - type: web
    name: my-express-api
    runtime: docker
    rootDir: server
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: income-mapper-db
          property: connectionString

  # Vite React Frontend
  - type: web
    runtime: static
    name: income-mapper-frontend
    env: node
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: REACT_APP_API_URL
        value: https://my-express-api.onrender.com
      - key: BACKEND_URL
        value: https://my-express-api.onrender.com/

  # SuperTokens Core
  - type: pserv
    runtime: docker
    name: supertokens-core
    rootDir: supertokens
    envVars:
      - key: POSTGRESQL_CONNECTION_URI
        value: postgresql://mydb_retv_user:cwktnt8t6vlEwb7AWs6JEfBiuEIvZXuu@dpg-cnf5k6la73kc73bsj7j0-a/mydb_retv
      - key: SUPERTOKENS_API_KEY
        value: your_api_key

# Specify environment variables for database access in SuperTokens and the backend app
# envVars:
#   - key: DATABASE_URL
#     fromDatabase:
#       name: my-postgres-db
#       property: connectionString

databases:
  - name: income-mapper-db
    databaseName: mydb
